apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: true
    tanzu.app.live.view.application.flavours: spring-boot
    tanzu.app.live.view.application.name: spring-sensors
    tanzu.app.live.view.application.port: 8080
    tanzu.app.live.view.application.actuator.port: 8081
spec:
  source:
    git:
      url: https://github.com/johnnyplatform/spring-sensors-rabbit.git
      ref:
        branch: main
  serviceClaims:
    - name: rmq
      ref:
        apiVersion: rabbitmq.com/v1beta1
        kind: RabbitmqCluster
        name: rmq-1

